export const CHAIR_COLORS = [
  { name: "Rojo", hex: "#e63946" },
  { name: "Naranja quemado", hex: "#d1441a" },
  { name: "Naranja", hex: "#fc8503" },
  { name: "Amarillo", hex: "#ffd60a" },
  { name: "Lima", hex: "#a3c614" },
  { name: "Verde", hex: "#3fa34d" },
  { name: "Verde selva", hex: "#0f7360" },
  { name: "Turquesa", hex: "#00b4d8" },
  { name: "Azul cielo", hex: "#4895ef" },
  { name: "Azul brillante", hex: "#2743f0" },
  { name: "Índigo", hex: "#3b2fa3" },
  { name: "Morado", hex: "#7d3cc9" },
  { name: "Lila", hex: "#b06bff" },
  { name: "Magenta", hex: "#cb1c85" },
  { name: "Rosa", hex: "#f15bb5" },
  { name: "Vino", hex: "#7b1e3d" },
  { name: "Azul grisáceo", hex: "#577590" },
  { name: "Azul marino", hex: "#1d3557" },
];
